### ISSUE TITLE
Make a Jupyter Book for the tutorials

### ISSUE THREAD

**Issue by leouieda** [fatiando/tutorials#4]
[JupyterBook](https://jupyterbook.org/intro.html) is an easy way to build a very nice sphinx website from Jupyter notebooks or even plain markdown files. The website includes links to download the content as notebooks and even run them on Binder. The setup is not very difficult and we could run it on CI and have the website served under fatiando.org/tutorials or tutorials.fatiando.org.

This could be a way to keep the tutorials in Markdown for easier development and still have the notebook for use in a live teaching setting. 

Any thoughts in favour or against this? 

cc @santisoler @aguspesce @andieie @MGomezN @LL-Geo 

> Some of these issues were raised in #3 by @MGomezN.

**Comment by MGomezN** [comment]
After checking the Quantitative Economics with Python
example... 
😮 
 I'm "A favor!"

**Comment by leouieda** [comment]
Hadn't seen that one before. It looks awesome! I really liked this one as well: https://inria.github.io/scikit-learn-mooc/index.html

**Comment by aguspesce** [comment]
It is a good idea!

**Comment by LL-Geo** [comment]
I like this as well!!!

**Comment by santisoler** [comment]
Great idea! JupyterBooks might be a great tool for uploading courses material, so implementing it on Fatiando tutorials is a great excuse to learn how do they work.

**Comment by MGomezN** [comment]
The Jupyter Book is alive! https://www.fatiando.org/tutorials/ As usual, I broke many things and had more questions than certainties. Stories for the next meeting :)

**Comment by MGomezN** [comment]
Fixed. See [commit](https://github.com/fatiando/tutorials/commit/ac0225720f1cd388dae0e4cc3ffdd839d158629a).
Improvement is needed. Specific features will be raised on the following issues.
